#ifndef VERSION_H
#define VERSION_H

#define _HS_MAJ_VERSION	1				//UPDATE THIS DEFINE ON VERSION CHANGE
#define _HS_MIN_VERSION	0				//UPDATE THIS DEFINE ON VERSION CHANGE

#define __STRINGIFY(x)		#x
#define _STRINGIFY(x)		__STRINGIFY(x)

#define HS_STR_VERSION 	_STRINGIFY(_HS_MAJ_VERSION._HS_MIN_VERSION)
#define HS_VSVI_VERSION	_HS_MAJ_VERSION,_HS_MIN_VERSION,0,0
#define HS_CRIGHT_YEARS	"2016-2017"		//UPDATE THIS DEFINE ON VERSION CHANGE

#endif //VERSION_H
